In [1]:
import numpy as np

## converting python sequences to numpy arrays

In [2]:
arr1d=np.array([1,2,3,4])
arr2d=np.array([[1,2],[3,4]])
arr1d,arr2d

(array([1, 2, 3, 4]), array([[1, 2],
        [3, 4]]))

## intrinsic numpy array creation functions

In [6]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.linspace(start=0,stop=1,num=9)

array([0.   , 0.125, 0.25 , 0.375, 0.5  , 0.625, 0.75 , 0.875, 1.   ])

In [8]:
np.eye(3) #3*3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [12]:
np.random.rand(2,3) #[0,1)

array([[0.74471301, 0.69261   , 0.76918551],
       [0.97257588, 0.34042239, 0.3642729 ]])

In [13]:
np.random.randn(2,3) #(0,1)

array([[ 0.36092706,  1.82216864, -1.94584178],
       [-0.00807784, -1.11267485,  0.10386823]])

In [26]:
print(arr1d)
print(arr1d[1])
print(arr2d)
print(arr2d[0][1],arr2d[0,1])
print(arr2d[:,1])
print(arr2d[0,0],arr2d[0,1])
print(arr2d[[0,0],[0,1]]) #2d, 

[1 2 3 4]
2
[[1 2]
 [3 4]]
2 2
[2 4]
1 2
[1 2]


In [28]:
arr2d[arr2d>2]

array([3, 4])

AttributeError: ignored